logging = "info"

[source]
url = "http://timeseries-db.docker.local:8086"
bucket = "power_monitoring"
org = "SHOESTRING"
token = "l3Z9k31lKzZ-Ixupk_s3FjinRas-HHbvf7tsBTpEUCP7m5YQL0Z0jF1yjQEC_ZNYLEr6xkSZfuXMUP_spHe9cg=="

[report]
time="00:00"
interval="1d"
window="1d"
sample_interval="10s"

[email.smtp]
host="smtp.office365.com"
port=587
timeout=5
username="your_email@outlook.com"
password="your_password"

[email]
to="recieving_email@cam.ac.uk"


