logging = "info" # module log level

[source]
url = "http://timeseries-db.docker.local:8086"
bucket = "production_tracking"
org = "SHOESTRING"
token = "l3Z9k31lKzZ-Ixupk_s3FjinRas-HHbvf7tsBTpEUCP7m5YQL0Z0jF1yjQEC_ZNYLEr6xkSZfuXMUP_spHe9cg=="

[report]
time="00:00"  # What time the first report should be sent
interval="1d" # How frequently reports should be sent
window="1d"   # How much data should be included in each report

[email]
send_email=false
to="your_recieving_email@outlook.com" # separate multiple recipient addresses with commas, all inside the double quotes

[email.smtp]
host="smtp.office365.com"
port=587
timeout=5
username="your_sending_email@outlook.com"
password="your_password"
